# Generated by Django 4.2.2 on 2023-07-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS_APP', '0002_employee_sale_saleitem_salesreport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
