# Generated by Django 4.2.2 on 2023-07-12 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS_APP', '0005_supplier_product_minimum_stock_product_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='description',
            new_name='contact_info',
        ),
    ]
