# Generated by Django 4.2.2 on 2023-07-14 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS_APP', '0009_sale_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='customer',
        ),
    ]
