# Generated by Django 4.2.2 on 2023-07-15 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS_APP', '0012_remove_saleitem_sale_sale_saleitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='saleitem',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='POS_APP.sale'),
        ),
    ]
