# Generated by Django 4.2.2 on 2023-07-15 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS_APP', '0013_remove_sale_saleitem_saleitem_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='sale',
        ),
        migrations.AddField(
            model_name='sale',
            name='saleitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='POS_APP.saleitem'),
        ),
    ]
