# Generated by Django 4.2.2 on 2023-08-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitems',
            name='profit',
            field=models.FloatField(default=0),
        ),
    ]
