# Generated by Django 4.2.2 on 2023-08-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0002_alter_saleitems_profit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='price',
            new_name='order_price',
        ),
        migrations.AddField(
            model_name='products',
            name='selling_price',
            field=models.FloatField(default=0),
        ),
    ]
