# Generated by Django 4.2.2 on 2023-08-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0003_rename_price_products_order_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.FloatField(default=1),
        ),
    ]
