# Generated by Django 4.2.2 on 2023-09-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0004_alter_products_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreport',
            name='grand_total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='total_profit',
            field=models.FloatField(default=0),
        ),
    ]
