# Generated by Django 4.2.2 on 2023-09-03 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0005_alter_salesreport_grand_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesreport',
            old_name='total_sales',
            new_name='No_of_sales',
        ),
        migrations.RenameField(
            model_name='salesreport',
            old_name='grand_total',
            new_name='total_sales_ammount',
        ),
    ]
